#!/bin/bash

eww open bar &
dunst &
swww init && swww img ~/Pictures/tokyo.gif &
mpd &
/usr/lib/lxpolkit/lxpolkit &
pipewire &
pipewire-pulse &
wireplumber &
$HOME/.config/hypr/components/import-gsettings &
hyprctl setcursor "Paper" 20 &
