#!/usr/bin/bash

case "${1}" in
    up) brightnessctl set 1%+ -q
    ;;
    down) brightnessctl set 1%- -q
    ;;
esac

notification() {

    BRIGHTNESS="$(brightnessctl info | grep 'Current brightness' | awk '{print $4}' | tr -d '()%')"
    
    if [ $BRIGHTNESS -eq 0 ]; then
        ICON="notification-display-brightness-off"
    elif [ $BRIGHTNESS -lt 10 ]; then
        ICON="notification-display-brightness-low"
    elif [ $BRIGHTNESS -lt 70 ]; then
	    ICON="notification-display-brightness-medium"
    elif [ $BRIGHTNESS -lt 100 ]; then
	    ICON="notification-display-brightness-high"
    else
        ICON="notification-display-brightness-full"
    fi

    exec notify-send "$BRIGHTNESS" -h "int:value:$BRIGHTNESS" -h string:synchronous:display-brightness -i $ICON -t 1000
    
}

notification
