#!/usr/bin/bash

case "${1}" in
    up) brightnessctl set 10%+ -q
    ;;
    down) brightnessctl set 10%- -q
    ;;
esac

notify() {

    BRIGHTNESS="$(brightnessctl info | grep 'Current brightness' | awk '{print $4}' | tr -d '()%')"
    
    if [ "$BRIGHTNESS" -lt 40 ]; then
        ICON="$HOME/.local/share/icons/status/bright_low.svg"
    elif [ "$BRIGHTNESS" -lt 70 ]; then
	    ICON="$HOME/.local/share/icons/status/bright_mid.svg"
    else
        ICON="$HOME/.local/share/icons/status/bright_ful.svg"
    fi

    exec notify-send "Brightness $BRIGHTNESS" -h "int:value:$BRIGHTNESS" -h string:synchronous:display-brightness -i $ICON -u low -t 1000
    
}

notify
