#!/usr/bin/bash

TIMESTAMP="$(date +%Y-%m-%d-%T)"
DIR="${HOME}/Pictures/Screenshots"
FILENAME="${DIR}/${TIMESTAMP}-screenshot.png"
ICON_SELECT="${HOME}/.local/share/icons/status/screen_reg.svg"

FRAME_COLOR="#939ab7"

# Directory check
[ -d "$DIR" ] || mkdir -p "$DIR"

notify() {
	notify-send "Picture obtained!" -h string:synchronous:screenshot -i $FILENAME -u low
}

shotfull() {
	grim "$FILENAME"
	notify
}

shotselection() {
	rm -f /tmp/grim_shot.png
	notify-send "Select region" -i $ICON_SELECT -h string:synchronous:screenshot -u low -t 1000 && \
		grim -g "$(slurp -w 0)" /tmp/grim_shot.png || \
			notify-send 'Screenshot canceled!' -h string:synchronous:screenshot -u low
	if [ -f "/tmp/grim_shot.png" ]; then
		convert /tmp/grim_shot.png \
			\( +clone -alpha extract -draw 'fill black polygon 0,0 0,10 10,0 fill white circle 10,10 10,0' \
			\( +clone -flip \) -compose Multiply -composite \
			\( +clone -flop \) -compose Multiply -composite \
			\) -alpha off -compose CopyOpacity -composite -quality 100% \
			miff:- | \
		convert - \
            \( +clone -background black -shadow 70x10+0+0 \
            \) +swap -background none -layers merge +repage -quality 100% \
			miff:- | \
	    convert - \
		    -bordercolor "$FRAME_COLOR" \
			-border 15 \
			-quality 100% \
		"$FILENAME" | wl-copy
	fi

	[ -f "$FILENAME" ] && notify
}

case "${1}" in
    full) shotfull
    ;;
    selc) shotselection
    ;;
esac
