#!/usr/bin/bash

case "${1}" in
    mute) wpctl set-mute @DEFAULT_SINK@ toggle
    ;;
    raise) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
    ;;
    lower) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    ;;
esac

notify() {

    MUTED="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $NF}')"
    VOLUME="$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | sed 's/%//g')"
    
    if [ "$MUTED" == "yes" ]; then
        MUTE="Muted"
        ICON="$HOME/.local/share/icons/status/volum_mut.svg"
    elif [ "$VOLUME" -lt 20 ]; then
        ICON="$HOME/.local/share/icons/status/volum_low.svg"
    elif [ "$VOLUME" -lt 60 ]; then
	    ICON="$HOME/.local/share/icons/status/volum_mid.svg"
    else
	    ICON="$HOME/.local/share/icons/status/volum_ful.svg"
    fi

    exec notify-send ${MUTE:-"Volume $VOLUME" -h "int:value:$VOLUME"} -h string:synchronous:audio-volume -i $ICON -u low -t 1000
    
}

notify
