#!/usr/bin/bash

CAPACITY="$(cat /sys/class/power_supply/BAT*/capacity)"
STATUS="$(cat /sys/class/power_supply/BAT*/status)"

icon() {
    [[ $STATUS == Charging ]] && echo "" && exit
    if [ "$CAPACITY" -gt "90" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "80" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "70" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "60" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "50" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "40" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "30" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "20" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "10" ]; then
	    icon=""
    elif [ "$CAPACITY" -gt "0" ]; then
	    icon=""
	    notify-send -u critical "Battery Low" "Connect Charger" -h string:synchronous:sys-battery
    else
        echo  && exit
    fi
    echo "$icon"
}

capacity() {
    echo "$CAPACITY"
}

status() {
	[[ "$STATUS" == "Not charging" ]] && STATUS="Full"
	echo "$CAPACITY% $STATUS"
}

uptimestatus() {
	UPTIME="$(uptime -p | sed -e 's/hour/hr/' -e 's/hours/hrs/' -e 's/minutes/mins/' -e 's/minute/min/' -e 's/up //')"
	echo "$UPTIME"
}

case "$1" in
	"icon") icon
	;;
	"capacity") capacity
	;;
	"status") status
	;;
	"uptime") uptimestatus
	;;
esac
