#!/usr/bin/bash

TIMESTAMP="$(date +%Y-%m-%d-%T)"
DIR="${HOME}/Videos/Screencast"
FILENAME="${DIR}/${TIMESTAMP}-screencast.mkv"
STAT="$(pgrep 'wf-recorder')"

indicator() {
	if [ -z ${STAT} ];then
        ICON="󰑊"
	    CLASS="lbl_screencast-indicator-n"
	else
        ICON="󰑋"
		CLASS="lbl-screencast-indicator-a"
	fi
    echo "(label :class \"$CLASS\" :text \"$ICON\")"
}

get_status_icon() {
	if [ -z "${STAT}" ]; then
		CURRENT_BUTTON="󰑊"
		CLASS="screencast-inactive"
    else
		CURRENT_BUTTON="󰑋"
		CLASS="screencast-active"
	fi
	echo $CURRENT_BUTTON
	echo $CLASS
}

start () {
	eww close screencast && eww close screencast-closer
	[[ -d "$DIR" ]] || mkdir -p "$DIR"
	if [ ! -z ${STAT} ]; then
		notify-send "Recording have been started" \
					-h string:synchronous:screen-record	
    else
	    for sec in $(seq 5 -1 1); do
			if [ "$sec" == 1 ]; then
				notify-send "Recording start" \
							-h string:synchronous:screen-record
				break
			fi
			notify-send "Recording in : $sec" \
						-h string:synchronous:screen-record \
						-u low
			sleep 1
		done
		wf-recorder -a -f "$FILENAME"
		eww close screencast && eww close screencast-closer
	fi
}

stop() {
	eww close screencast && eww close screencast-closer
	pkill -2 wf-recorder && \
	    notify-send "Record Stop" \
					-h string:synchronous:screen-record || \
			notify-send "Exit with do nothing" \
						-h string:synchronous:screen-record
}

case "$1" in
	"indicator") indicator
	;;
	"status_icon") get_status_icon | head -n1
	;;
	"status_class") get_status_icon | tail -n1
	;;
	"start") start
	;;
	"stop") stop
	;;
esac
