#!/usr/bin/bash

STATUS="$(cat /sys/class/net/w*/operstate)"
SIGNAL="$(iwconfig wlan0 | awk '/Signal level/ { print $4 }' | sed 's/level=-//')"

icon() {
    [[ $STATUS == down || -z "$SIGNAL" ]] && echo "󰤭" && exit
    if [ "$SIGNAL" -lt "20" ]; then
	    icon="󰤨"
    elif [ "$SIGNAL" -lt "40" ]; then
	    icon="󰤥"
    elif [ "$SIGNAL" -lt "60" ]; then
        icon="󰤢"
    elif [ "$SIGNAL" -lt "80" ]; then
      	icon="󰤟"
    elif [ "$SIGNAL" -lt "100" ]; then
        icon="󰤯"
    fi
    echo "$icon"
}

percent() {
    echo $PERCEN
}

case "$1" in
	"icon") icon
    ;;
    "percent") percent
    ;;
esac
