#!/usr/bin/bash

STATUS="$(cat /sys/class/net/w*/operstate)"
SIGNAL="$(nmcli device wifi | awk '/\*/{if (NR!=1) {print $8}}')"

icon() {
    [[ $STATUS == down || -z "$SIGNAL" ]] && echo "󰤭" && exit
    if [ "$SIGNAL" -gt "80" ]; then
	    icon="󰤨"
    elif [ "$SIGNAL" -gt "50" ]; then
	    icon="󰤥"
    elif [ "$SIGNAL" -gt "30" ]; then
        icon="󰤢"
    elif [ "$SIGNAL" -gt "10" ]; then
      	icon="󰤟"
    elif [ "$SIGNAL" -gt "0" ]; then
        icon="󰤯"
    fi
    echo "$icon"
}

percent() {
    echo $PERCEN
}

case "$1" in
	"icon") icon
    ;;
    "percent") percent
    ;;
esac
