#!/usr/bin/bash

STATUS="$(cat /sys/class/net/w*/operstate)"

WRSTATUS="$(nmcli device status | grep ' wifi ' | awk '{print $3}')"
[[ "$WRSTATUS" == "connected" ]] && WRNAME="$(nmcli device status | grep ' wifi ' | awk '{print $4}')"
[[ -z "$WRNAME" ]] || SIGNAL="$(nmcli device wifi | grep $WRNAME | sed -e "s|$WRNAME||" | awk '{print $8}')"

icon() {
    [[ "$STATUS" == down || -z "$SIGNAL" ]] && echo "󰤭" && exit
    if [ "$SIGNAL" -gt "80" ]; then
	    icon="󰤨"
    elif [ "$SIGNAL" -gt "50" ]; then
	    icon="󰤥"
    elif [ "$SIGNAL" -gt "30" ]; then
        icon="󰤢"
    elif [ "$SIGNAL" -gt "10" ]; then
      	icon="󰤟"
    elif [ "$SIGNAL" -gt "0" ]; then
        icon="󰤯"
    fi
    echo "$icon"
}

case "$1" in
	"icon") icon
    ;;
esac
