#!/usr/bin/bash

#initial check for occupied workspaces
ownum="$(hyprctl workspaces | grep ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')')"
for num in $ownum; do 
  export o"$num"="$num"
done

#initial check for focused workspace
ofnum="$(hyprctl monitors | grep active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')')"
for num in $ofnum; do 
  export f"$num"="$num"
  export fnum=f"$num"
done

workspaces() {
    if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
        unset -v "$fnum"
        num=${1:11}
        export f"$num"="$num"
        export fnum=f"$num"

    elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
        num=${1:17}
        export o"$num"="$num"
        export f"$num"="$num"

    elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
        num=${1:18}
        unset -v o"$num" f"$num"
    fi

    #output eww widget
    echo   "(box :orientation \"v\" :class \"workspace\" :space-evenly \"false\" \
                (button :onclick \"hyprctl dispatch workspace 1\" :class \"0$o1$f1\" \"\") \
                (button :onclick \"hyprctl dispatch workspace 2\" :class \"0$o2$f2\" \"\") \
                (button :onclick \"hyprctl dispatch workspace 3\" :class \"0$o3$f3\" \"\") \
                (button :onclick \"hyprctl dispatch workspace 4\" :class \"0$o4$f4\" \"\") \
            )"
    
}

workspaces
socat2 -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
    workspaces "$event"
done
